# Generated by Django 5.0.7 on 2024-07-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("profile_summary", models.CharField(max_length=250)),
                ("education", models.TextField(blank=True)),
                ("skills", models.TextField()),
                ("work_experience", models.TextField(blank=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
