# Generated by Django 5.0.7 on 2024-07-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ResumePage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="email",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="resume",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="resume",
            name="profile_summary",
            field=models.TextField(),
        ),
    ]
